### ISSUE TITLE
Check whether the pdflatex exists.

### ISSUE THREAD

**Issue by sungmin817** [szhorvat/MaTeX#1]
I tested your package today and found it was very helpful. After configuration, however, I had to spend some time since I could not get correct results. It turned out that I only configured the directories where the pdflatex lives but did not specify pdflatex (i.e., /some/other/directory/ not /some/other/directory/pdflatex).  However, it did not warn me but yielded errors few lines after when it tried to run ghostscript(that is why I initially doubted that my ghostscript configuration was wrong). It would be nice if you add some codes that check whether pdflatex is correctly configured.  IMO, DirectoryQ[ path]` is sufficient for this check.  

By the way, thank you for your nice package. I really like it.

**Comment by szhorvat** [comment]
Thanks for point this out.  I included a quick check to make sure the path points to a file (not a directory).  

This part os the package needs to be reworked eventually, it is true that it only does a few rudimentary checks.
