### ISSUE TITLE
compatibility with ghostscript 9.21

### ISSUE THREAD

**Issue by JaegerP** [szhorvat/MaTeX#13]
Hi there, I have problems running MaTeX against ghostscript release 9.21 on Arch linux. It seems MaTeX does not recognize the binary as a valid ghostscript:

`/usr/bin/gs is either not working or is not Ghostscript.`
`Please configure Ghostscript using ConfigureMaTeX["Ghostscript" -> "path to gs executable..."]`

Quick fix:
Build ghostscript-9.20 from source and run
`ConfigureMaTeX["Ghostscript" -> "/path/to/gs-9.20/bin/gs"]`

If you need any more information, please let me know.

**Comment by szhorvat** [comment]
Please restore the 9.21 that didn't work, evaluate [the troubleshooting notebook](http://szhorvat.net/pelican/files/MaTeX-Troubleshooting.nb), and email it to me. There is nothing special about 9.21 that should prevent it from working.  The results from that notebook will help me track down and fix the problem.

Also, make sure you are using the latest version. There was a fix for a similar problem in 1.7.0.

**Comment by JaegerP** [comment]
I found that my system libz is version 1.2.11, instead of 1.2.9 which MaTeX tries to load. The libpng in the Mathematica folder is a v1.12, but gs-9.21 recommends using v1.16. Maybe that's the problem here.

**Comment by szhorvat** [comment]
Fixed by 3062104749a71d726d1a3e8b0fb9f9c916ed143f

**Comment by Dmarc** [comment]
Hi there,

I have the same configuration, and so the same issue... Is there a way to install the latest (unstable) version of MaTeX that includes the last commits (including the fix 3062104) from sources, or do I have to wait for the next official paclet file to download ?
Thanks for this great, helpful, job !

**Comment by szhorvat** [comment]
@Dmarc I'm going to try to release it next week (if I can get around to completing a new tutorial in the documentation).  If you need it earlier, feel free to send me an email, and I'll send you a paclet that has the fix (sans the documentation changes I'm working on).

**Comment by szhorvat** [comment]
@Dmarc  The new release is out now.

**Comment by Dmarc** [comment]
It's working like a charm ! Thanks a lot.
