### ISSUE TITLE
If I just install the basical MiKTeX,could I can use your MaTex?

### ISSUE THREAD

**Issue by Juddd** [szhorvat/MaTeX#16]
If I just install the [basical MiKTeX](http://i.stack.imgur.com/SqIQK.png) in [here](https://miktex.org/2.9/setup),could I can use your MaTex?

Note in my system,the `pdflatex` is in

![](http://i.stack.imgur.com/ofAtf.png)

The `Ghostscript` is in

![](http://i.stack.imgur.com/iQqv1.png)

But this code does't work..And I cannot use your package still.

![Mathematica graphics](http://i.stack.imgur.com/dKo4S.png)

**Comment by szhorvat** [comment]
You need to set the path to the executables, not the directories containing them.

There are packages that are required but not part of the basic MiKTeX. These should be auto-installed by MiKTeX when they are first used. The list is on the MaTeX page (standalone, exscale, lmodern, but maybe I missed something).

**Comment by Juddd** [comment]
@szhorvat My `gswin32c` is version `8.64` after I install [this package](http://i.stack.imgur.com/L8Ta5.png) and this [update wizard](https://miktex.org/howto/update-miktex) cannot update the `Ghostscript`.I know this version is not supported by your package.So I download a new version from [here](https://www.ghostscript.com/download/gsdnld.html).Now I used
```
ConfigureMaTeX[
 "pdfLaTeX" -> 
  "C:\\Program Files\\MiKTeX \
2.9\\miktex\\bin\\x64\\miktex-pdftex.exe", 
 "Ghostscript" -> "C:\\Program Files\\gs\\gs9.21\\bin\\gswin64c.exe"]
```

in this time.As the [output](http://i.stack.imgur.com/EKx5z.png),it has been config successfully.But it seem I cannot use a `Matex` package.Help please.

**Comment by szhorvat** [comment]
> But it seem I cannot use a Matex package.Help please.

If there is a problem, you need to be very specific and provide all details.  There is also a troubleshooting section as well as a tutorial in the builtin documentation.  Open the docs and search for MaTeX.
