### ISSUE TITLE
Too slow when I specify the FontSize

### ISSUE THREAD

**Issue by Juddd** [szhorvat/MaTeX#18]
I don't sure this is a bug or not, but when I specify a custom FontSize, the speed will be very slow..
![](https://i.stack.imgur.com/oBB7g.png)

**Comment by szhorvat** [comment]
This is not a bug. You are seeing the effect of caching. It's explained in the tutorial:

    Documentation`HelpLookupPacletURI["MaTeX/tutorial/TypesettingWithMaTeX#286546638"]

(It's the Improving Performance section in case that above link doesn't work.)
