### ISSUE TITLE
installation issue on windows

### ISSUE THREAD

**Issue by Foadsf** [szhorvat/MaTeX#20]
When I put the .paclet file in the Downloads folder on windows 10 and run the command: 

> PacletInstall["~/Downloads/MaTeX-1.7.2.paclet"]

It does not work. What worked for me to put it on Documents folder and then run:

> PacletInstall["MaTeX-1.7.2.paclet"]

**Comment by szhorvat** [comment]
`"~/Downloads/MaTeX-1.7.2.paclet"` is an example.  This is not even a valid path specification on Windows.  You need to put in the full path to the `.paclet` file, wherever it is.  It does not matter where you downloaded it to.
