### ISSUE TITLE
"Failed to import PDF" on first run

### ISSUE THREAD

**Issue by mskblackbelt** [szhorvat/MaTeX#25]
Just downloaded the latest version (1.7.4) on a Mac running Mathematica 11.3.0 and macOS 10.14.3. After initializing (`Needs...`), I see no outputs. Trying to evaluate `MaTeX["x^2"]` gives the errors:

    Import: Cannot import data as PDF format
    Failed to import PDF. This is unexpected. Please go to https://github.com/szhorvat/MaTeX and create a bug report.

**Comment by szhorvat** [comment]
I need more information about your setup. Please download the notebook and follow the instructions within.

**Comment by szhorvat** [comment]
Somehow the link went missing. Please download this notebook:

 - http://szhorvat.net/pelican/files/MaTeX-Troubleshooting.nb

and follow the instructions within.

Also let me know what TeX system you are using, and if you have installed any instances of Ghostscript yourself (with MacPorts, Homebrew or from elsewhere)

**Comment by mskblackbelt** [comment]
body{font-family:Helvetica,Arial;font-size:13px}I’ve attached the evaluated notebook. I tried with both pdfLaTeX and LuaLaTeX as the typesetting engines, but quickly skimming the output suggests that maybe the issue is with Mathematica… Let me know what other information I can provide.   – Dustin Wheelermskblackbelt@me.com On February 28, 2019 at 05:13:10, Szabolcs Horvát (notifications@github.com) wrote: 





Somehow the link went missing. Please download this
notebook:

http://szhorvat.net/pelican/files/MaTeX-Troubleshooting.nb

and follow the instructions within.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by szhorvat** [comment]
Can you tell me what TeX system you are using? If you are unsure, show me where you downloaded it from.

Did you ever manually (separately) install Ghostscript, or are you using the Ghostscript that came with your TeX system?  If you did, where did you obtain Ghostscript from?

**Comment by mskblackbelt** [comment]
body {
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	padding:1em;
	margin:auto;
	background:#fefefe;
}

h1, h2, h3, h4, h5, h6 {
	font-weight: bold;
}

h1 {
	color: #000000;
	font-size: 28pt;
}

h2 {
	border-bottom: 1px solid #CCCCCC;
	color: #000000;
	font-size: 24px;
}

h3 {
	font-size: 18px;
}

h4 {
	font-size: 16px;
}

h5 {
	font-size: 14px;
}

h6 {
	color: #777777;
	background-color: inherit;
	font-size: 14px;
}

hr {
	height: 0.2em;
	border: 0;
	color: #CCCCCC;
	background-color: #CCCCCC;
    display: inherit;
}

p, blockquote, ul, ol, dl, li, table, pre {
	margin: 15px 0;
}

a, a:visited {
	color: #4183C4;
	background-color: inherit;
	text-decoration: none;
}

#message {
	border-radius: 6px;
	border: 1px solid #ccc;
	display:block;
	width:100%;
	height:60px;
	margin:6px 0px;
}

button, #ws {
	font-size: 12 pt;
	padding: 4px 6px;
	border-radius: 5px;
	border: 1px solid #bbb;
	background-color: #eee;
}

code, pre, #ws, #message {
	font-family: Monaco;
	font-size: 10pt;
	border-radius: 3px;
	background-color: #F8F8F8;
	color: inherit;
}

code {
	border: 1px solid #EAEAEA;
	margin: 0 2px;
	padding: 0 5px;
}

pre {
	border: 1px solid #CCCCCC;
	overflow: auto;
	padding: 4px 8px;
}

pre > code {
	border: 0;
	margin: 0;
	padding: 0;
}

#ws { background-color: #f8f8f8; }


.bloop_markdown table {
border-collapse: collapse;  
font-family: Helvetica, arial, freesans, clean, sans-serif;  
color: rgb(51, 51, 51);  
font-size: 15px; line-height: 25px;
padding: 0; }

.bloop_markdown table tr {
border-top: 1px solid #cccccc;
background-color: white;
margin: 0;
padding: 0; }
     
.bloop_markdown table tr:nth-child(2n) {
background-color: #f8f8f8; }

.bloop_markdown table tr th {
font-weight: bold;
border: 1px solid #cccccc;
margin: 0;
padding: 6px 13px; }

.bloop_markdown table tr td {
border: 1px solid #cccccc;
margin: 0;
padding: 6px 13px; }

.bloop_markdown table tr th :first-child, table tr td :first-child {
margin-top: 0; }

.bloop_markdown table tr th :last-child, table tr td :last-child {
margin-bottom: 0; }

.bloop_markdown blockquote{
  border-left: 4px solid #dddddd;
  padding: 0 15px;
  color: #777777; }
  blockquote > :first-child {
    margin-top: 0; }
  blockquote > :last-child {
    margin-bottom: 0; }

code, pre, #ws, #message {
    word-break: normal;
    word-wrap: normal;
}

hr {
    display: inherit;
}

.bloop_markdown :first-child {
    -webkit-margin-before: 0;
}

code, pre, #ws, #message {
    font-family: Menlo, Consolas, Liberation Mono, Courier, monospace;
}


.send { color:#77bb77; }
.server { color:#7799bb; }
.error { color:#AA0000; }All of the TeX and GS binaries were downloaded as part of the MacTeX 2018 release and managed with TeX Live Utility. 

body{font-family:Helvetica,Arial;font-size:13px}  – Dustin Wheelermskblackbelt@me.com On February 28, 2019 at 09:55:28, Szabolcs Horvát (notifications@github.com) wrote: 





Can you tell me what TeX system you are using? If you are
unsure, show me where you downloaded it from.
Did you ever manually (separately) install Ghostscript, or are
you using the Ghostscript that came with your TeX system? If you
did, where did you obtain Ghostscript from?
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by szhorvat** [comment]
There are problems with your email. Can you either use the GitHub interface, or just email me directly? My address is at the beginning of the troubleshooting notebook. I believe that the latest MacTeX has Ghostscript 9.23 and you have 9.26.  Do you have any idea why that might be?

**Comment by szhorvat** [comment]
In fact it's better if you just email me directly until we sort everything out. I think it'll take a bit of experimentation. I have the same setup that you say you have. I would like to find the differences.

**Comment by szhorvat** [comment]
Summary of the outcome:

Ghostscript was installed using Homebrew. This version of Ghostscript kept crashing for some reason (possibly because it was used unsupported CPU instructions).

When a process started with `RunProcess` crashes, currently Mathematica returns the ExitCode as `None` (i.e. not a numerical quantity). The exit code was checked using `!=` which does not evaluate for non-numerical quantities, and thus MaTeX did not report Ghostscript's failure.

A partial fix was committed in 2a1a685f1dd708247ac1fe9bec36be57034288bb
