### ISSUE TITLE
"Ghostscript version 9.07 found.  MaTeX requires Ghostscript 9.15 or later." error with gs 9.27

### ISSUE THREAD

**Issue by seadra** [szhorvat/MaTeX#28]
The only ghostscript version installed on my system (Linux) is 9.27, but MaTeX gives the error:

"Ghostscript version 9.07 found.  MaTeX requires Ghostscript 9.15 or later."

I tried running

`ConfigureMaTeX[ "pdfLaTeX" -> "/usr/bin/pdflatex", "Ghostscript" -> "/usr/bin/gs" ]` but it changed nothing.

```
$ which gs
/usr/bin/gs
$ /usr/bin/gs --version
9.27
```

**Comment by szhorvat** [comment]
Please restart Mathematica, then evaluate the following:

```mma
PacletInformation["MaTeX"]

Needs["MaTeX`"]

ConfigureMaTeX[]

RunProcess[{"/usr/bin/gs", "--version"}]

MaTeX`Private`runProcess[{"/usr/bin/gs", "--version"}]

$Line
```

Post the output here.

**Comment by szhorvat** [comment]
I should note that I can see absolutely no way that this error would be shown unless you really are running Ghostscript version 9.07. The version shown in the error is the unprocessed string returned by `gs --version`.

**Comment by seadra** [comment]
Hi,

Thanks for the prompt reply!

I found the culprit. The notebook was using a remote kernel, on a computer which has gs 9.07 installed. I assume there is no feasible way to force MaTeX to use the local gs instead of the remote one, so I guess this should be closed

**Comment by szhorvat** [comment]
>  I assume there is no feasible way to force MaTeX to use the local gs

That is correct. MaTeX can only see the computer on which the Mathematica kernel is running. You could install a newer Ghostscript on the remote computer, even into your home directory. You can get binaries at https://www.ghostscript.com/download/gsdnld.html but I do not know if they will work on a distro so old that it only ships 9.07 ...
