### ISSUE TITLE
MaTeX fails to load

### ISSUE THREAD

**Issue by B7ADE-RUNNER** [szhorvat/MaTeX#30]
**I am having issue with loading MaTeX.**

__________________________________________

(Debug) In[18]:= << MaTeX`

(Debug) During evaluation of In[18]:= Get::noopen: Cannot open MaTeX`.

(Debug) Out[18]= $Failed

_____________________________________________________

**The built-in command ResourceFunction doesn't appear to be defined.**

(Debug) In[19]:= ResourceFunction["MaTeXInstall"][]

(Debug) Out[19]= ResourceFunction["MaTeXInstall"][]

_____________________________________________________
**I cannot reinstall**

(Debug) In[16]:= Needs["PacletManager`"]
PacletInstall["/full/path/to/MaTeX-1.7.5.paclet"]

(Debug) During evaluation of In[16]:= PacletInstall::fnotfound: Paclet file /full/path/to/MaTeX-1.7.5.paclet not found.

(Debug) Out[17]= $Failed

_________________________________________________________________________

**Comment by szhorvat** [comment]
> I am having issue with loading MaTeX.

MaTeX is not installed on your computer.

> The built-in command ResourceFunction doesn't appear to be defined.

As noted in the instructions, this installation method is available only in Mathematica 11.3 or later.

> I cannot reinstall

You must type in the actual path to the paclet file that you download. 

If you are not sure what a file path is, type `PacletInstall[`, then use the menu item Insert -> File Path..., browse to the paclet file and select it, finally type the closing `]` and evaluate the cell.

**Comment by B7ADE-RUNNER** [comment]
Oh you know I didn't see that. I am not sure where the paclet file is on the computer. I recently updated Mathematica on this system to 11.1, and I have alternated between student and full versions so I am not sure what is going on with the file system where Mathematica is looking. Thank you for bringing that too my attention.

**Comment by B7ADE-RUNNER** [comment]
I did install it oh so many semesters ago. I just can't seem to find where the files ended up.

**Comment by szhorvat** [comment]
> I am not sure where the paclet file is on the computer.

It is the file that you downloaded from https://github.com/szhorvat/MaTeX/releases 

> I did install it oh so many semesters ago.

If ``<<MaTeX` `` fails then it is not installed now.

----

I suggest you simply use the `updateMateX[]` function here: https://github.com/szhorvat/MaTeX#upgrading-or-uninstalling  Then you do not need to bother with paths.

**Comment by B7ADE-RUNNER** [comment]
Thank you for this. Looks like it is suggesting to me to update ghostscript too. I can now load it in with the Needs[] command or the other way <<. I really like MaTeX. Thank you very much.

**Comment by szhorvat** [comment]
I'll close this issue now.

If you have suggestions about how to make the installation instructions easier to follow, please let me know, and I will try to improve them.

**Comment by B7ADE-RUNNER** [comment]
Everything is fine, that was extremely easy, I was just tripping
