### ISSUE TITLE
MaTeX load returns error but can work.

### ISSUE THREAD

**Issue by asukaminato0721** [szhorvat/MaTeX#34]
I recently updated to MMA 12.1, and decided to continue using MaTeX.
When I run 

    <<MaTeX`

in 12.1 , I see this:
![image](https://user-images.githubusercontent.com/30024051/77070755-b5b0a700-69e2-11ea-82ec-dfbaa7af8613.png)
But as you can see, it works!
To test, I run it on MMA 11.3.

![image](https://user-images.githubusercontent.com/30024051/77070813-d4af3900-69e2-11ea-80a0-f88713de39ee.png)

Nothing wrong.

After that , I decided to add  it in `init.m` . But each time I use MMA, it shows
![image](https://user-images.githubusercontent.com/30024051/77071176-7fbff280-69e3-11ea-96ad-227ee2b321fc.png)

Which is annoying. So is there any way to deal with it?

**Comment by szhorvat** [comment]
Can you please evaluate [the troubleshooting notebook](http://szhorvat.net/pelican/files/MaTeX-Troubleshooting.nb) and email it to me? Let's figure out what is going wrong.

**Comment by asukaminato0721** [comment]
Done it.













At 2020-03-21 07:58:20, "Szabolcs Horvát" <notifications@github.com> wrote:

Can you please evaluate the troubleshooting notebook and email it to me? Let's figure out what is going wrong.

**Comment by szhorvat** [comment]
Thanks! This happened because your `PATH` environment variable contained an empty entry (i.e. it has two consecutive `;`).

MaTeX should suppress messages from this, but the message name changed between 11.3 and 12.0.

This will be fixed in the next release.

**Comment by szhorvat** [comment]
New release that suppresses this error in 12.0 and 12.1 is out now.
