### ISSUE TITLE
"/usr/bin/gs is either not working or is not a command line version of Ghostscript."

### ISSUE THREAD

**Issue by mauricioquintela** [szhorvat/MaTeX#35]
The only version of Ghstscript installed in my system (Linux) is 9.53.1, running Mathematica 12.1.

When configuring MaTeX, the error 
"/usr/bin/gs is either not working or is not a command line version of Ghostscript." is presented, making MaTeX unable to be used. 

Both 
```
RunProcess[{"/usr/bin/gs", "--version"}]

MaTeX`Private`runProcess[{"/usr/bin/gs", "--version"}]
```
return 
```
<|"ExitCode" -> 0, "StandardOutput" -> "9.53.1
  ", "StandardError" -> ""|>
```
Furthermore,  Ghostscript works in terminal and `~ > which gs ` returns `/usr/bin/gs`, as expected.

**Comment by szhorvat** [comment]
This is likely because of the unusual version number. In the past, Ghostscript was always x.y, but this is an x.y.z pattern version. I'll look into it.

**Comment by szhorvat** [comment]
Thanks for the report! [Version 1.7.7](https://github.com/szhorvat/MaTeX/releases/tag/v1.7.7) fixes this problem.

**Comment by mauricioquintela** [comment]
Thank you for the quick fix.
