### ISSUE TITLE
Build a PacletSite in this github repository

### ISSUE THREAD

**Issue by rnotlnglgq** [szhorvat/MaTeX#37]
With this improvement, users can simply write `PacletInstall["MaTeX"]` to fetch the newest and compatible version of MaTeX after executing `PacletSiteRegister@"https://github.com/szhorvat/MaTeX/raw/master"`.

Put all paclets in the `/Paclets/` directory, and export the `PacletSite[Paclet[Name->..., ...], ...]` expression as ZIP to `/PacletSite.mz`, then everything will be OK.

You can use the `PutSiteInfo[]` function to conveniently create `PacletSite.mz` in this paclet:
`PacletInstall["WolframPacletSiteManager", "Site"->"https://github.com/rnotlnglgq/WolframPacletSiteManager/raw/master"]` .

https://mathematica.stackexchange.com/questions/218254/how-to-set-up-own-paclet-server/243689

**Comment by szhorvat** [comment]
I would prefer to avoid maintaining my own private paclet server. MaTeX is actually already on this paclet server (and will be updated there soon): https://paclets.github.io/PacletServer/ 

I believe Wolfram Research has been working on an official paclet repository for quite a while now. When it is released, I will definitely submit MaTeX there. 

It would be best not to live in a world where each project runs its own private paclet server. That would not provide much of an advantages over just publishing the `.paclet` files on GitHub Releases.
